listener:
  kind: rfc2136
  rfc2136:
    addr: :5454
    clients:
      - name: tst.
        secret: NzBjOTU4OTVlOTZlOTg5OGQwYTUxYTdjNWYzNTI3NzA5YjIyZTIxNWVjOTc3NWMxNzIxZjdjN2ExNjliNDc1ZCAgLQo=
        xfr_allowed: true
        zones:
          - test.lala.
        types:
          - txt

upstream:
  kind: adguard
  adguard:
    api_server_url: https://g.buglloc.cc
    login: buglloc
    password: kek-cheburek
    auto_ptr: true
  cloudflare:
    zone_id: c74b3a3b1002eba34d6cb7f8a62b69da
    token: 3f786850e387550fdab836ed7e6dc881de23001b
