listener:
  kind: rfc2136
  rfc2136:
    addr: :5454
    clients:
      - name: tst.
        secret: NzBjOTU4OTVlOTZlOTg5OGQwYTUxYTdjNWYzNTI3NzA5YjIyZTIxNWVjOTc3NWMxNzIxZjdjN2ExNjliNDc1ZCAgLQo=
        xfr_allowed: true
        zones:
          test.lala.
upstream:
  kind: adguard
  adguard:
    api_server_url: https://g.buglloc.cc
    login: buglloc
    password: kek-cheburek
    auto_ptr: true